# Generated by Django 5.2.14 on 2026-05-09 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("A1", "A1 — Replenishment window"),
                            ("A2", "A2 — Capture window"),
                            ("A3", "A3 — Commodity churn detected"),
                            ("A4", "A4 — Technical product churn"),
                            ("A5", "A5 — Order anomaly"),
                            ("A6", "A6 — Hidden friction signal"),
                            ("A7", "A7 — Early warning"),
                            ("A8", "A8 — Return / cancellation risk"),
                            ("A9", "A9 — Pre-churn signal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "model_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M0", "M0 — Customer segmentation"),
                            ("M1", "M1 — Replenishment prediction"),
                            ("M2", "M2 — Commodity churn"),
                            ("M3", "M3 — Technical product churn"),
                            ("M4", "M4 — Return risk"),
                            ("M5", "M5 — Pre-churn signal"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Natural language explanation generated by the model",
                    ),
                ),
                (
                    "affected_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recommended_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALES_REP", "Sales representative"),
                            ("TELEMARKETER", "Telemarketer"),
                            ("MARKETING_AUTO", "Marketing automation"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "economic_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated annual revenue at risk (EUR)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "urgency_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days before the situation becomes critical",
                        null=True,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField(db_index=True, unique=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["client_id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "analytical_block",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("family", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="AlertNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="api.alert",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="api.client",
            ),
        ),
        migrations.CreateModel(
            name="ClientPotential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family", models.CharField(max_length=100)),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "potential_value",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potentials",
                        to="api.client",
                    ),
                ),
            ],
            options={
                "ordering": ["client", "family"],
            },
        ),
        migrations.CreateModel(
            name="CSVUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv_uploads/")),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("CLIENTS", "Clients (Clientes.csv)"),
                            ("PRODUCTS", "Products (Productos.csv)"),
                            ("SALES", "Sales (Ventas.csv)"),
                            ("POTENTIALS", "Potentials (Potencial.csv)"),
                            ("CAMPAIGNS", "Campaigns (Campañas.csv)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial (with errors)"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("rows_total", models.IntegerField(default=0)),
                ("rows_processed", models.IntegerField(default=0)),
                ("rows_failed", models.IntegerField(default=0)),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="JSON list of row-level errors"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(db_index=True, max_length=50)),
                ("date", models.DateTimeField()),
                ("units", models.DecimalField(decimal_places=4, max_digits=12)),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="api.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "priority"], name="api_alert_status_698aae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["client", "status"], name="api_alert_client__c152f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type"], name="api_alert_alert_t_e1fa27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientpotential",
            unique_together={("client", "family")},
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["date"], name="api_sale_date_61ee18_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["client", "date"], name="api_sale_client__d371c8_idx"
            ),
        ),
    ]
